const types = {
    REQUEST: 'REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    GET_SCORE: 'GET_SCORE',
    GET_SCORE_FAILURE: 'GET_SCORE_FAILURE',
    LOGIN_SAGA: 'LOGIN_SAGA'
}

export default types;